[build]
  command = "pip install -r netlify/functions/requirements.txt -t netlify/functions/"
  functions = "netlify/functions"
  publish = "frontend/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.api]
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 