[build]
  command = "pip install -r netlify/functions/api/requirements.txt -t netlify/functions/api/"
  functions = "netlify/functions"
  publish = "frontend/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 